# Generated by Django 3.0.4 on 2020-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_modules', models.BooleanField()),
                ('default_action', models.CharField(choices=[('RTH', 'Return to Home'), ('HOVER', 'Hover'), ('LAND', 'Land'), ('TELEM', 'Disable Telemetry'), ('ALERT', 'Alert Only')], default='RTH', max_length=6)),
                ('default_initiate_time', models.IntegerField()),
                ('default_return_time', models.IntegerField()),
                ('connection_method', models.CharField(choices=[('GCS', 'Local GCS'), ('DIRECT', 'Direction Connection')], default='GCS', max_length=6)),
            ],
        ),
    ]
