# Generated by Django 3.0.4 on 2020-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcsclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_initiate_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_return_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='enabled_modules',
            field=models.BooleanField(default=0),
        ),
    ]
