# Generated by Django 3.0.4 on 2020-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcsclient', '0002_auto_20200403_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='enabled_modules',
            new_name='dos_enabled',
        ),
        migrations.AddField(
            model_name='settings',
            name='gps_enabled',
            field=models.BooleanField(default=0),
        ),
    ]
